const data = {
  event_type:'boda',
  nombre_novia:'Tania',
  nombre_novio:'Jesús',
  nombre_papa_novia:'Arturo Arumir Jimenez',
  nombre_mama_novia:'Yolanda Calderón Álvarez',
  nombre_papa_novio:'Héctor Orozco Reyes',
  nombre_mama_novio:'Prima Gonzalez Abrego',
  frase:'Quienes estan destinados a ser, Siempre acaban siendo.',
  img_header:'cover.png',
  img_fondo1:'img-1.png',
  img_fondo2:'img-2.png',
  fecha_dia:'30',
  fecha_mes:'Diciembre',
  fecha_year:'2024',
  religiosa_hora:'',
  religiosa_lugar:'',
  religiosa_direccion:'',
  religiosa_direccion_col:'',
  religiosa_direccion_cd:'',
  religiosa_ubicacion:'',
  recepcion_hora:'19:00',
  recepcion_lugar:'salon Oasis',
  recepcion_direccion:'blvd h. colegio militar s/n',
  recepcion_direccion_col:'las americas II',
  recepcion_direccion_cd:'Iguala de la Independencia, Guerrero',
  recepcion_ubicacion:'https://maps.app.goo.gl/qfyRxW24dXefNLAVA',
  confirmacion_novia:'7331569892',
  confirmacion_novio:'7331576092',
}

export default data