const data = {
  event_type:'boda',
  nombre_novia:'Tania Lizbeth',
  nombre_novio:'Jesús Naarai',
  nombre_papa_novia:'Gustavo Flores Rangel',
  nombre_mama_novia:'Maricruz Sánchez Peralta',
  nombre_papa_novio:'Moises Barrios Díaz',
  nombre_mama_novio:'Maurilia Carreón Ortíz',
  nombre_padrino:'Sr. Jesús Flores Mota',
  nombre_madrina:'Sra. Blanca Estela Rangel Román',
  frase:'Hay momentos en la vida que son muy especiales por si solos, pero al compartirlo con personas tan especiales como tú se convierten en momentos imposibles de olvidar',
  img_header:'',
  img_fondo1:'flor1.png',
  img_fondo2:'flor2.png',
  fecha_dia:'23',
  fecha_mes:'Noviembre',
  fecha_year:'2024',
  religiosa_hora:'18:00',
  religiosa_lugar:'Iglesia de San Gerardo María Mayela',
  religiosa_direccion:'Mariano Abasolo, 56',
  religiosa_direccion_col:'Centro',
  religiosa_direccion_cd:'Iguala de la Independencia',
  religiosa_ubicacion:'https://maps.app.goo.gl/s7ok8ZWnHPttUjDr6',
  recepcion_hora:'19:00',
  recepcion_lugar:'salon Oasis',
  recepcion_direccion:'blvd h. colegio militar s/n',
  recepcion_direccion_col:'las americas II',
  recepcion_direccion_cd:'Iguala de la Independencia, Guerrero',
  recepcion_ubicacion:'https://maps.app.goo.gl/qfyRxW24dXefNLAVA',
  confirmacion_novia:'7332944639',
  confirmacion_novio:'7335841579',
}

export default data